apiVersion: v1
kind: Service
metadata:
  name: spore-registry
  namespace: sporevm-system
  labels:
    app.kubernetes.io/name: spore-registry
    app.kubernetes.io/part-of: sporevm-k8s
spec:
  selector:
    app.kubernetes.io/name: spore-registry
    app.kubernetes.io/part-of: sporevm-k8s
  ports:
    - name: https
      port: 5000
      targetPort: https
