{{- if and .Values.agent.enabled .Values.agent.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sporevm-k8s.agentServiceAccountName" . }}
  labels:
    app.kubernetes.io/name: spore-agent
    {{- include "sporevm-k8s.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
